name: .NET Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore -p:PackageVersion=1.0.${{ github.run_number }}
    - name: Publish Nuget package
      # You may pin to the exact commit or the version.
      # uses: myci-actions/publish-nuget@fe315834b49173c9502c4787904cd9093aa29131
      uses: myci-actions/publish-nuget@5
      with:
        # nuget package filename, wildcards allowed
        filename: "*.nupkg"
        # API key to access the repository
        api-key: ${{secrets.NUGET_API_KEY}}
